---
- hosts: webserver
  become: true
  tasks:
    - name: install web components
      apt:
        name: ['apache2', 'libapache2-mod-wsgi', 'python-pip', 'python-virtualenv']
        state: present
        update_cache: yes

 

 

